version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: CodeMyth
    ports:
      - "3306:3306"
    networks:
      - student
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot:
    image: ganesh1326/student-result:latest
    container_name: springboot-container
    ports:
      - "5050:5050"
    networks:
      - student
    depends_on:
      mysql:
        condition: service_healthy

networks:
  student:
    driver: bridge
