apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: student-result
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS CodeMyth;
    USE CodeMyth;
    create table IF NOT EXISTS student(
    ID bigint NOT NULL auto_increment,
    NAME varchar (100) default NULL,
    CITY VARCHAR(50) default NULL,
    MARKS integer default NULL,
    RESULT boolean default false,
    CREATED_DATE timestamp default current_timestamp,
    primary key(ID));

