# Student-Result Application Service
apiVersion: v1
kind: Service
metadata:
  name: student-result-service
  namespace: student-result
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5050
    nodePort: 30005
  selector:
    app: student-app
